/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the applicable 
 * Liferay software end user license agreement ("License Agreement")
 * found on www.liferay.com/legal/eulas. You may also contact Liferay, Inc.
 * for a copy of the License Agreement. You may not use this file except in
 * compliance with the License Agreement. 
 * See the License Agreement for the specific language governing
 * permissions and limitations under the License Agreement, including 
 * but not limited to distribution rights of the Software.
 *
 */

package com.liferay.hu.badge.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Subscriber service. Represents a row in the &quot;BadgePortlet_Subscriber&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.hu.badge.service.model.impl.SubscriberModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.hu.badge.service.model.impl.SubscriberImpl}.
 * </p>
 *
 * @author Borkuti Peter
 * @see Subscriber
 * @see com.liferay.hu.badge.service.model.impl.SubscriberImpl
 * @see com.liferay.hu.badge.service.model.impl.SubscriberModelImpl
 * @generated
 */
@ProviderType
public interface SubscriberModel extends BaseModel<Subscriber>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subscriber model instance should use the {@link Subscriber} interface instead.
	 */

	/**
	 * Returns the primary key of this subscriber.
	 *
	 * @return the primary key of this subscriber
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subscriber.
	 *
	 * @param primaryKey the primary key of this subscriber
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the subscriber ID of this subscriber.
	 *
	 * @return the subscriber ID of this subscriber
	 */
	public long getSubscriberId();

	/**
	 * Sets the subscriber ID of this subscriber.
	 *
	 * @param subscriberId the subscriber ID of this subscriber
	 */
	public void setSubscriberId(long subscriberId);

	/**
	 * Returns the group ID of this subscriber.
	 *
	 * @return the group ID of this subscriber
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this subscriber.
	 *
	 * @param groupId the group ID of this subscriber
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this subscriber.
	 *
	 * @return the company ID of this subscriber
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this subscriber.
	 *
	 * @param companyId the company ID of this subscriber
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this subscriber.
	 *
	 * @return the user ID of this subscriber
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this subscriber.
	 *
	 * @param userId the user ID of this subscriber
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this subscriber.
	 *
	 * @return the user uuid of this subscriber
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this subscriber.
	 *
	 * @param userUuid the user uuid of this subscriber
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this subscriber.
	 *
	 * @return the user name of this subscriber
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this subscriber.
	 *
	 * @param userName the user name of this subscriber
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this subscriber.
	 *
	 * @return the create date of this subscriber
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this subscriber.
	 *
	 * @param createDate the create date of this subscriber
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this subscriber.
	 *
	 * @return the modified date of this subscriber
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this subscriber.
	 *
	 * @param modifiedDate the modified date of this subscriber
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the subscriber user ID of this subscriber.
	 *
	 * @return the subscriber user ID of this subscriber
	 */
	public long getSubscriberUserId();

	/**
	 * Sets the subscriber user ID of this subscriber.
	 *
	 * @param subscriberUserId the subscriber user ID of this subscriber
	 */
	public void setSubscriberUserId(long subscriberUserId);

	/**
	 * Returns the subscriber user uuid of this subscriber.
	 *
	 * @return the subscriber user uuid of this subscriber
	 */
	public String getSubscriberUserUuid();

	/**
	 * Sets the subscriber user uuid of this subscriber.
	 *
	 * @param subscriberUserUuid the subscriber user uuid of this subscriber
	 */
	public void setSubscriberUserUuid(String subscriberUserUuid);

	/**
	 * Returns the badge type of this subscriber.
	 *
	 * @return the badge type of this subscriber
	 */
	public long getBadgeType();

	/**
	 * Sets the badge type of this subscriber.
	 *
	 * @param badgeType the badge type of this subscriber
	 */
	public void setBadgeType(long badgeType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Subscriber subscriber);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Subscriber> toCacheModel();

	@Override
	public Subscriber toEscapedModel();

	@Override
	public Subscriber toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}