/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the applicable 
 * Liferay software end user license agreement ("License Agreement")
 * found on www.liferay.com/legal/eulas. You may also contact Liferay, Inc.
 * for a copy of the License Agreement. You may not use this file except in
 * compliance with the License Agreement. 
 * See the License Agreement for the specific language governing
 * permissions and limitations under the License Agreement, including 
 * but not limited to distribution rights of the Software.
 *
 */

package com.liferay.hu.badge.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.hu.badge.service.model.Subscriber;

/**
 * The extended model base implementation for the Subscriber service. Represents a row in the &quot;BadgePortlet_Subscriber&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubscriberImpl}.
 * </p>
 *
 * @author Borkuti Peter
 * @see SubscriberImpl
 * @see Subscriber
 * @generated
 */
@ProviderType
public abstract class SubscriberBaseImpl extends SubscriberModelImpl
	implements Subscriber {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subscriber model instance should use the {@link Subscriber} interface instead.
	 */
}